### ISSUE TITLE
💊 [GitHub Actions] Solution for resolving issue with generating test report

### ISSUE THREAD

**Issue by ylazakovich** [selenide/selenide#2704]
## The problem
Currently not only selenide doesn't able to generate test-report 
And as result after trying to read downloaded report users get:
https://github.com/selenide/selenide/actions/runs/8492079805
> Error: HTTPError: Response code 400 (Authentication information is not given in the correct format. Check the value of Authorization header.)

## Details
It has started reproducing since upgrading `actions/upload-artifact` from `v3` to `v4`
https://github.com/selenide/selenide/pull/2589

I have found few confirmations of this issue:
1) https://github.com/dorny/test-reporter/issues/343
2) https://github.com/dorny/test-reporter/issues/363

## Suggestions for resolving issue
1) The simplest solution: change `actions/upload-artifact` `v4` to `v3`
2) Workaround from the comment: https://github.com/dorny/test-reporter/issues/343#issuecomment-1872325556 
- Stay with `actions/upload-artifact@v4` 
- Use `actions/checkout@v4` and  `actions/download-artifact@v4`
```yaml
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          run-id: ${{ github.event.workflow_run.id }}
      - uses: dorny/test-reporter@v1
        with:
#          artifact: /test-report-(.*)-(.*)/
#          name: 'Test report: $1 $2'
          name: 'Test report'
          path: '**/build/test-results/**/TEST-*.xml'
          reporter: java-junit
```
