### ISSUE TITLE
JdkWebSocket initial request execution error

### ISSUE THREAD

**Issue by MakarenkoNikita** [selenide/selenide#3044]
If I try to download a file via CDP from Selenium Grid, I encounter the following exception. "JdkWebSocket initial request execution error". This is relevant for com.codeborne:selenide-appium:7.9.2 and selenium/hub:4.32.0-20250505, selenium/node-chrome:4.32.0-20250505.
The issue can be reproduced from the following [project](https://github.com/IlyaUk/JavaProject)

Command used to start Selenium Grid with Docker
```
version: "3"
services:
  kz-hub:
    image: selenium/hub:4.32.0-20250505
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    environment:
      - SE_ENABLE_TRACING=false
    healthcheck:
      test: "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"
      interval: "15s"
      timeout: "30s"
      retries: 5
    restart: always

  chrome:
    image: selenium/node-chrome:4.32.0-20250505
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_MAX_INSTANCES=1
      - SE_OPTS=--enable-managed-downloads true
      - SE_ENABLE_TRACING=false
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    restart: always
    deploy:
      mode: replicated
      replicas: 1
```
